name: Github Context

on: workflow_dispatch

jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
    
      - name: Print Repo Name
        run: | 
          echo 'Repo Name ${{github.repository}}'
          echo 'Repo Id ${{github.repository_id}}'
          echo 'Repo url ${{github.repositoryUrl}}'
          echo 'Repo token ${{github.token}}'
          echo 'Workflow Name ${{github.workflow}}'
          echo 'Actor ${{github.actor}}'
          echo 'Ref Details ${{github.ref}}'
          echo 'Trigger event ${{github.event_name}}'
          echo 'Run id${{github.run_id}}'
          echo 'Run number ${{github.run_number}}'
