name: Run Java Program

on: workflow_dispatch
env:
  JAVA_VERSION: '17'
jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: microsoft
      - name: Print Java version
        run: java -version

  compile-java:   
     needs: setup-java
     runs-on: ubuntu-latest
     outputs:
      compile_message: ${{steps.set_output.outputs.message }}

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Print Repo Name
         run: | 
          echo 'Repo Name ${{github.repository}}'
          echo 'Repo Id ${{github.repository_id}}'
          echo 'Repo url ${{github.repositoryUrl}}'
          echo 'Repo token ${{github.token}}'
          echo 'Workflow Name ${{github.workflow}}'
          echo 'Actor ${{github.actor}}'
          echo 'Ref Details ${{github.ref}}'
          echo 'Trigger event ${{github.event_name}}'
          echo 'Run id${{github.run_id}}'
          echo 'Run number ${{github.run_number}}'
          echo 'env variable ${{env.JAVA_VERSION}}'

       - name: Compile Java Code
         if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.actor == 'aggarwalsparsh' && env.JAVA_VERSION == '17'
         run: javac src/HelloWorld.java

       - name: Set output message
         id: set_output
         run: echo "message=Java compilation successful" >> $GITHUB_OUTPUT

  display_msg:
    needs: compile-java
    runs-on: ubuntu-latest
    steps: 

      - name: Displaying message
        run: echo '${{needs.compile-java.outputs.compile_message }}'
         
       - name: Run Java Program
         if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.actor == 'aggarwalsparsh' && env.JAVA_VERSION == '17'
         run: java -cp src HelloWorld
